### ISSUE TITLE
Printed sheet does not have link where to get newer version

### ISSUE THREAD

**Issue by paulvi** [pellaton/eclipse-cheatsheet#7]
We can print and hand out, but developers will not know were to get newer.

Please add <https://github.com/pellaton/eclipse-cheatsheet> link somewhere

**Comment by pellaton** [comment]
That's a great idea! Will be added with the final version for Eclipse Neon planned for today.

**Comment by pellaton** [comment]
added a github project link to the document footer

**Comment by paulvi** [comment]
Thanks
